### ISSUE TITLE
AlpineJS x-transition directive

### ISSUE THREAD

**Issue by Blabbone** [TechAkayy/frameworks-lite-for-pinegrow#2]
The plugin replaces, within the project, the x-transition attribute with x-transition="true".
The correct syntax accepts only "x-transition", without the value true.
Reference to AlpineJS documentation:
https://alpinejs.dev/directives/transition.

I recommend removing this directive.

**Comment by TechAkayy** [comment]
Thanks for raising this issue @Blabbone. I just released v1.1.1, and fixed an issue related to this behaviour. 

A value is always needed for now within the control to be able to use the clear-icon. I will add this info to the docs. The `true` is displayed only within the control. But in the actual attribute, the `true` is not added. Any other value will be in sync. 



Let me know if v1.1.1 works for. you. Cheers!  

![image](https://github.com/TechAkayy/frameworks-lite-for-pinegrow/assets/73772701/0b270804-6e38-4b42-9fab-15a5648fcf33)

![image](https://github.com/TechAkayy/frameworks-lite-for-pinegrow/assets/73772701/97353070-a678-404f-8d06-f161c3df44ae)

**Comment by TechAkayy** [comment]
Just released v1.2.0 that fixes this issue fully - https://github.com/TechAkayy/frameworks-lite-for-pinegrow/releases/tag/v1.2.0

- Directives input box now includes both a clear icon and a delete icon. Previously, truthy directives were displayed as `true` in the control, but not anymore. It will always be in sync with the actual attribute key-value pairs. This also fixes https://github.com/TechAkayy/frameworks-lite-for-pinegrow/issues/2.

	![image](https://github.com/TechAkayy/frameworks-lite-for-pinegrow/assets/73772701/e0ca6137-eadf-42c4-9d4e-7f14ba745c0a)
	![image](https://github.com/TechAkayy/frameworks-lite-for-pinegrow/assets/73772701/6ec987ed-83be-4f97-80c6-7e9573230d10)

Please re-open if you still face any issues.
